import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        canvas: '#16110f',
        surface: '#211a17',
        'surface-container': '#251e1b',
        'surface-container-low': '#211a17',
        'surface-container-high': '#302825',
        'surface-container-highest': '#3b3330',
        'surface-container-lowest': '#130d0a',
        'surface-dim': '#18120f',
        'surface-bright': '#403734',
        'surface-tint': '#ffb59e',
        'surface-hover': '#2a211c',
        primary: '#ffb59e',
        'primary-container': '#ea6a40',
        'primary-hover': '#d45a30',
        'primary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#ffb59e',
        'on-primary': '#5e1700',
        'on-primary-container': '#521300',
        'on-primary-fixed': '#3a0b00',
        'on-primary-fixed-variant': '#842500',
        secondary: '#f3be67',
        'secondary-fixed': '#ffdead',
        'secondary-fixed-dim': '#f3be67',
        'on-secondary': '#432c00',
        'on-secondary-fixed': '#281900',
        'on-secondary-fixed-variant': '#5f4400',
        tertiary: '#61d6ed',
        'tertiary-fixed-dim': '#61d6ed',
        'tertiary-container': '#049fb5',
        'on-tertiary': '#00363f',
        'on-tertiary-fixed': '#001f25',
        'on-tertiary-fixed-variant': '#004e5a',
        'on-tertiary-container': '#002f36',
        border: '#3a322d',
        outline: '#a68b82',
        'outline-variant': '#58423b',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'text-primary': '#ece0dc',
        'text-secondary': '#a89c93',
        'text-muted': '#7a706a',
        'text-on-accent': '#16110f',
        'on-surface': '#eee0da',
        'on-background': '#eee0da',
        'inverse-surface': '#eee0da',
        'inverse-on-surface': '#372f2b',
        'inverse-primary': '#a73a13',
        background: '#18120f',
        'status-success': '#4a7c59',
        'status-error': '#c44d4d',
        'status-warning': '#d4a24e',
        'status-info': '#5b8fb9',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-xl': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl-mobile': ['2.5rem', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display': ['2.5rem', { lineHeight: '1.15', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-mobile': ['2rem', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-1': ['1.5rem', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-2': ['1.25rem', { lineHeight: '1.35', fontWeight: '600' }],
        'headline-3': ['1.125rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-large': ['1.125rem', { lineHeight: '1.6' }],
        'body-default': ['1rem', { lineHeight: '1.6' }],
        'body-small': ['0.875rem', { lineHeight: '1.5' }],
        'caption': ['0.75rem', { lineHeight: '1.5' }],
        'overline': ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.08em' }],
        'label-mono': ['0.75rem', { lineHeight: '1.4' }],
      },
      spacing: {
        'margin': '1.5rem',
        'gutter': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
      },
      boxShadow: {
        'forge-glow': '0 0 25px rgba(232, 105, 63, 0.35)',
        'forge-lg': '0 10px 40px -10px rgba(0, 0, 0, 0.7), 0 0 20px rgba(232, 105, 63, 0.15)',
      },
      animation: {
        'ember-glow': 'emberPulse 6s ease-in-out infinite',
      },
      keyframes: {
        emberPulse: {
          '0%, 100%': { opacity: '0.6', transform: 'scale(1)' },
          '50%': { opacity: '0.95', transform: 'scale(1.05)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
